env                   = "dev"

vpc_cidr              = "10.1.0.0/16"
public_subnet_a_cidr  = "10.1.1.0/24"
public_subnet_b_cidr  = "10.1.2.0/24"
private_subnet_a_cidr = "10.1.3.0/24"
private_subnet_b_cidr = "10.1.4.0/24"
multi_az              = "false"
allocated_storage     = "10"
skip_final_snapshot   = "true"
ssh_key_name          = "postgre"
private_key_path      = "postgre.pem"
num_bastion_host      = "2"
num_app               = "2"
instance_type_bastion_host      = "t2.micro"
instance_type_app     = "t2.medium"
